server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: "134511130qq"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: peZW-moPPxVqGgQSRyMKhclumFpQpznKTqWc5tHW
  secretKey: X7VHxbXqwfaS4n_LwPAyGDpvENm_zmL9fd92mEj1
  bucket: liuris
  baseurl: http://rsj6jcall.bkt.clouddn.com/